/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DraggableItem: typeof import('./src/components/DraggableItem.vue')['default']
    DraggableList: typeof import('./src/components/DraggableList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
    TheItem: typeof import('./src/components/TheItem.vue')['default']
    TheList: typeof import('./src/components/TheList.vue')['default']
  }
}
